#!/bin/bash

scriptdir="$(dirname "$0")"
cd "$scriptdir"
export SCRIPTDIR="$PWD"

[ "$1" = "--osx" ] && DOSBOX_Binary="$SCRIPTDIR/bin/dosbox.osx" 
[ "$1" = "--linux" ] && DOSBOX_Binary="$SCRIPTDIR/bin/dosbox.linux"  
[ "$1" = "--linux" ] && OS="linux"

[ "$DOSBOX_Binary" = "" ] && exit 1
 
shift 

[ "$1" = "" ] && exit 

rm -rf "/tmp/winebuild-dosbox" 2> /dev/null

mkdir -p "/tmp/winebuild-dosbox"
cd "/tmp/winebuild-dosbox"

tar -xvf "$SOURCEDIR/$1"

cd "/tmp/winebuild-dosbox/bin" 
mv "wine" "wine.real"
cp "$DOSBOX_Binary" "DOSBox"
cp "$SCRIPTDIR"/bin/wine* ./

if [ "$OS" == "linux" ]; then
	cd "/tmp/winebuild-dosbox/lib"
	cp "$SCRIPTDIR"/lib/* ./
fi

cd "/tmp/winebuild-dosbox/share"
cp -r "$SCRIPTDIR"/share/* ./

destination="${1/-upstream/-dos_support-upstream}"
cd "/tmp/winebuild-dosbox/" 

tar czvf "$destination" ./
shasum "$destination" > "$destination.sha1"
